### ISSUE TITLE
Swiss tournament

### ISSUE THREAD

**Issue by Krzychumag** [cutechess/cutechess#542] opened 2019-11-18 21:44 UTC
Can you once again ask for making the program the opportunity to play Swiss tournaments.
I have asked once, now please again. Please take care of this first and don't write to wait a few more years.

**Comment by alwey** [comment] 2019-11-19 09:18
This is a duplicate of #267.

Please refrain from opening new issues for a request already made.
If everybody did this, the project would not move forward but it would be much more difficult to track the issues.

**Comment by Krzychumag** [comment] 2019-11-20 07:05
Thank you alwey.

**Comment by alwey** [comment] 2019-11-22 19:43
Please close this issue.

**Comment by artoj** [comment] 2020-06-25 17:18
Closed as duplicate.

**Closed by artoj** 2020-06-25 17:18 UTC
