### ISSUE TITLE
hangs

### ISSUE THREAD

**Issue by flok99** [cutechess/cutechess#27] opened 2016-02-10 12:22 UTC
Hi,

Sometimes cutechess-cli hangs. That may be caused by engines getting stuck. I would like to suggest a timeout or so so that those processes are terminated after a bit.

**Comment by ilaripih** [comment] 2016-02-11 08:02
Hello,

There are already all sorts of timeouts for cases where an engine takes too long to respond, does not terminate when asked, etc. If cutechess hangs at any point, it's a bug that I'd really like to fix, but I need more information:

* How often does this happen? Can you easily reproduce the problem?
* What cutechess settings are you using? If you can paste the whole command line string, that would be great.
* Does the problem happen during a game, between games, or at the beginning of a match?
* Can you run the match with the -debug parameter, save the output to a file and post the contents here?

**Comment by flok99** [comment] 2016-02-12 08:44
Hi,

The situation is a cluster of 12 raspberry-pi2s. When I run a test during the night then most of the time around 3 of them hang somewhere during the night.
bandril	39:12:05	2016-02-12 07:25:44
crinoth	161:53:25	2016-02-12 09:18:25
diplos	39:03:28	2016-02-12 04:58:17
enlandia	161:50:20	2016-02-12 09:20:43
gallifrey	10:30:58	2016-02-12 09:21:37
jul	261:22:04	2016-02-12 05:22:05
...
bandril, diplos and jul are hanging here.

cutechess settings:
cutechess-cli \
        -engine cmd=./E_2006c2b.sh proto=uci \
        -engine cmd=./E_2006c2b-2.sh proto=uci \
        -engine cmd=./E_1_2001-lmr.sh proto=uci \
        -engine cmd=./E_1_2045.sh proto=uci \
        -engine cmd=./E_1_2065.sh proto=uci \
        -engine cmd=./E_1_2065_2045.sh proto=uci \
        -engine cmd=./E_1_2067.sh proto=uci \
        -engine cmd=./E_1_2067b.sh proto=uci \
        -engine cmd=./E_1_2067_2045.sh proto=uci \
        -engine cmd=./E_1_2067_2065.sh proto=uci \
        -engine cmd=./E_1_2067_2065_2045.sh proto=uci \
        -engine cmd=/usr/local/bin/tscp181 proto=xboard \
        -concurrency $CONC \
        -each tc=40/30+0.25 dir=$DIR -rounds 1 -recover -pgnout out/$HOST.pgn -site "$HOST" -debug 2>&1 | tee -a hang_$HOST.log

CONC=2, DIR=/home/folkert/QueenBee, HOST=hostname of current system e.g. diplos
Those scripts (E_1_something.sh) are symbolic links to wrapper.sh which is:
#! /bin/sh

ME=$0
NOSH=`echo $ME | sed -e 's/.sh$//g'`
HOST=`hostname`

exec $NOSH -c 1 -H 192 -l `pwd`/$HOST.trace

As you it does an exec. So the script+shell is replaced by the chess engine binary.
It seems to happen at the end of a game.

A couple of logfiles:
http://vps001.vanheusden.com/~folkert/hang_bandril.log.gz
http://vps001.vanheusden.com/~folkert/hang_diplos.log.gz
http://vps001.vanheusden.com/~folkert/hang_jul.log.gz

**Comment by ilaripih** [comment] 2016-02-12 15:30
Thanks a bunch for the logs! I'll analyze them further on Sunday. Based on a quick look it reminds me very much of the problems that were fixed in the cutechess 0.7.x series. What cutechess version are you using, is it based on the latest master branch commits?

**Comment by flok99** [comment] 2016-02-12 16:20
Oh indeed it is 0.7.2. I downloaded it somewhere before 2015/11/11.

I'll give the latest github version a try.

On Fri, Feb 12, 2016 at 3:30 PM, Ilari Pihlajisto <notifications@github.com>
wrote:

> Thanks a bunch for the logs! I'll analyze them further on Sunday. Based on
> a quick look it reminds me very much of the problems that were fixed in the
> cutechess 0.7.x series. What cutechess version are you using, is it based
> on the latest master branch commits?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cutechess/cutechess/issues/27#issuecomment-183374796>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl

**Comment by flok99** [comment] 2016-02-12 16:45
Installed it and it is now running (12x).
Please note that the current github version also says it is 0.7.2.

On Fri, Feb 12, 2016 at 4:20 PM, Folkert van Heusden <mail@vanheusden.com>
wrote:

> Oh indeed it is 0.7.2. I downloaded it somewhere before 2015/11/11.
>
> I'll give the latest github version a try.
>
> On Fri, Feb 12, 2016 at 3:30 PM, Ilari Pihlajisto <
> notifications@github.com> wrote:
>
>> Thanks a bunch for the logs! I'll analyze them further on Sunday. Based
>> on a quick look it reminds me very much of the problems that were fixed in
>> the cutechess 0.7.x series. What cutechess version are you using, is it
>> based on the latest master branch commits?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cutechess/cutechess/issues/27#issuecomment-183374796>
>> .
>>
>
>
>
> --
> www.vanheusden.com  www.slimwinnen.nl
>



-- 
www.vanheusden.com  www.slimwinnen.nl

**Comment by ilaripih** [comment] 2016-02-14 11:24
Thanks! The version still says 0.7.2 because that's still the last released version. If upgrading cutechess to the latest master doesn't fix the problem, it would be interesting to see what happens if TSCP is removed from the tournament. Xboard protocol 1 engines (eg. TSCP) are difficult to keep in sync with the GUI because they don't support the "ping" commad.

**Comment by flok99** [comment] 2016-02-15 08:11
Hi,

Tried it without tscp but then it also hangs.
http://vps001.vanheusden.com/~folkert/hang_bandril.log.gz
http://vps001.vanheusden.com/~folkert/hang_crinoth.log.gz

**Comment by ilaripih** [comment] 2016-02-15 12:27
Okay, so now it's just UCI engines in the tournament? That narrows things down nicely. If I manage to reproduce this I'm fairly confident I'll be able to fix it.

**Comment by flok99** [comment] 2016-02-15 13:10
Yes, only UCI.
It is doing fairly simple UCI, this version:
http://chessdb.sourceforge.net/tutorial/engine-interface.txt

On Mon, Feb 15, 2016 at 1:27 PM, Ilari Pihlajisto <notifications@github.com>
wrote:

> Okay, so now it's just UCI engines in the tournament? That narrows things
> down nicely. If I manage to reproduce this I'm fairly confident I'll be
> able to fix it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cutechess/cutechess/issues/27#issuecomment-184186454>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl

**Comment by flok99** [comment] 2016-02-15 23:43
Tonight 6 systems hung. At least 4 of them after a 3-fold repetition end.
One of those 3-fold rep systems had at that time only 3 chess programs
running; I would expect 4 (concurrency 2). The 3 that still were running
were waiting for commands from cutechess-cli.

On Mon, Feb 15, 2016 at 1:09 PM, Folkert van Heusden <mail@vanheusden.com>
wrote:

> Yes, only UCI.
> It is doing fairly simple UCI, this version:
> http://chessdb.sourceforge.net/tutorial/engine-interface.txt
>
> On Mon, Feb 15, 2016 at 1:27 PM, Ilari Pihlajisto <
> notifications@github.com> wrote:
>
>> Okay, so now it's just UCI engines in the tournament? That narrows things
>> down nicely. If I manage to reproduce this I'm fairly confident I'll be
>> able to fix it.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cutechess/cutechess/issues/27#issuecomment-184186454>
>> .
>>
>
>
>
> --
> www.vanheusden.com  www.slimwinnen.nl
>



-- 
www.vanheusden.com  www.slimwinnen.nl

**Comment by ilaripih** [comment] 2016-02-16 08:10
I'll have more time to debug this today after work. I'm pretty sure the problem is either terminating an engine or starting one (cutechess-cli does that in the middle of tournaments that have more than 2 players). Is your Raspberry Pi the 4-core version, with a 32-bit Linux? And do you get any output in stderr from cutechess-cli?

**Comment by flok99** [comment] 2016-02-16 08:45
Yes, the 4-core model with 32b linux.
No stderr visible.

On Tue, Feb 16, 2016 at 8:10 AM, Ilari Pihlajisto <notifications@github.com>
wrote:

> I'll have more time to debug this today after work. I'm pretty sure the
> problem is either terminating an engine or starting one (cutechess-cli does
> that in the middle of tournaments that have more than 2 players). Is your
> Raspberry Pi the 4-core version, with a 32-bit Linux? And do you get any
> output in stderr from cutechess-cli?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cutechess/cutechess/issues/27#issuecomment-184569076>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl

**Comment by flok99** [comment] 2016-02-16 09:16
This morning:
3 down
system 1: 3 programs running
system 2: 3 programs running
system 3: 3 programs running
Last night I enabled core-files. No core files found so it are no segfaults
in my programs.
So for some reason one exits and this is not seen by cutechess-cli.

On Tue, Feb 16, 2016 at 8:45 AM, Folkert van Heusden <mail@vanheusden.com>
wrote:

> Yes, the 4-core model with 32b linux.
> No stderr visible.
>
> On Tue, Feb 16, 2016 at 8:10 AM, Ilari Pihlajisto <
> notifications@github.com> wrote:
>
>> I'll have more time to debug this today after work. I'm pretty sure the
>> problem is either terminating an engine or starting one (cutechess-cli does
>> that in the middle of tournaments that have more than 2 players). Is your
>> Raspberry Pi the 4-core version, with a 32-bit Linux? And do you get any
>> output in stderr from cutechess-cli?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cutechess/cutechess/issues/27#issuecomment-184569076>
>> .
>>
>
>
>
> --
> www.vanheusden.com  www.slimwinnen.nl
>



-- 
www.vanheusden.com  www.slimwinnen.nl

**Comment by ilaripih** [comment] 2016-02-16 10:18
Yes - either cutechess-cli doesn't see that an engine exits or it fails to start the engine. I can easily test many variations of these conditions.

**Comment by flok99** [comment] 2016-02-16 11:28
If I can do anything, let me know.

On Tue, Feb 16, 2016 at 10:18 AM, Ilari Pihlajisto <notifications@github.com
> wrote:

> Yes - either cutechess-cli doesn't see that an engine exits or it fails to
> start the engine. I can easily test many variations of these conditions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cutechess/cutechess/issues/27#issuecomment-184610359>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl

**Comment by flok99** [comment] 2016-02-16 15:28
Also odd: sometimes it looks like the pgn-file is not updated.
You see here that it is still running (hang_diplos):

16:22:44 1d folkert@belle:/data/QueenBee↥ QueenBee(16) ‡ ls -la
out/diplos.pgn hang_diplos.log -rw-r--r-- 1 folkert folkert 252346735 Feb
16 16:23 hang_diplos.log
-rw-r--r-- 1 folkert folkert   3917163 Feb 16 14:40 out/diplos.pgn

but the output (diplos.pgn) is from hours ago. Also in the last 5 minutes a
couple of new games started so it is not one game that played for hours.


On Tue, Feb 16, 2016 at 11:28 AM, Folkert van Heusden <mail@vanheusden.com>
wrote:

> If I can do anything, let me know.
>
> On Tue, Feb 16, 2016 at 10:18 AM, Ilari Pihlajisto <
> notifications@github.com> wrote:
>
>> Yes - either cutechess-cli doesn't see that an engine exits or it fails
>> to start the engine. I can easily test many variations of these conditions.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cutechess/cutechess/issues/27#issuecomment-184610359>
>> .
>>
>
>
>
> --
> www.vanheusden.com  www.slimwinnen.nl
>



-- 
www.vanheusden.com  www.slimwinnen.nl

**Comment by ilaripih** [comment] 2016-02-16 17:07
PGN update halts because cutechess-cli wants to write the games in chronological order (according to game number), and if it's still waiting for the "finished" signal from game N it's not going to write games N+1, N+2 etc. Now I just need to figure out why some games never finish.

**Comment by ilaripih** [comment] 2016-02-16 17:13
Can you try what happens without the "-recover" option?

**Comment by ilaripih** [comment] 2016-02-16 17:59
I looked more closely at the hang_crinoth.log file and I think I found the culprit:

At timestamp 2455988 there's:

`2455988 >UciEngine(105): uci`

Later at roughly 2518237:

`Terminating process of engine UciEngine(105)`
`Warning: Forfeit type 6: player UciEngine has no side`

So cutechess-cli sends the engine the "uci" command but the engine (I guess) crashes, cutechess-cli notices it. But cutechess-cli does not handle it well when the engine hangs or crashes before responding to the initial "uci" command and the whole tournament stalls.

I hope I can find time to fix this soon.

**Comment by flok99** [comment] 2016-02-17 07:41
Hi,

This "no side" thing is interesting and odd: I see no core-files and I
don't think there's an other way for my program to terminate early.
Does cutechess also have a debug-mode for the i/o send to/read from a chess
program?

On Tue, Feb 16, 2016 at 6:59 PM, Ilari Pihlajisto <notifications@github.com>
wrote:

> I looked more closely at the hang_crinoth.log file and I think I found the
> culprit:
>
> At timestamp 2455988 there's:
>
> 2455988 >UciEngine(105): uci
>
> Later at roughly 2518237:
>
> Terminating process of engine UciEngine(105)
> Warning: Forfeit type 6: player UciEngine has no side
>
> So cutechess-cli sends the engine the "uci" command but the engine (I
> guess) crashes, cutechess-cli notices it. But cutechess-cli does not handle
> it well when the engine hangs or crashes before responding to the initial
> "uci" command and the whole tournament stalls.
>
> I hope I can find time to fix this soon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cutechess/cutechess/issues/27#issuecomment-184801129>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl

**Comment by ilaripih** [comment] 2016-02-17 12:35
The "no side" warning happens because cutechess-cli forced the engine to forfeit the game, but the engine wasn't even really started. The delay between the initial "uci" command and terminating the engine was about 62 seconds, so maybe the the engine just hung for a minute and then the QProcess module which cutechess-cli uses, terminated the process. I'll check if QProcess has a 60 second timeout somewhere...

Cutechess-cli's "-debug" parameter should write all engine I/O to stdout.

**Comment by ilaripih** [comment] 2016-02-17 13:05
I pushed a commit that prints an error message if writing to an engine fails: https://github.com/cutechess/cutechess/commit/89b610a31418ab5db14716021f0acdba078e2fa8
That could help debug the problem where cutechess-cli doesn't get a response to the "uci" command.

**Comment by ilaripih** [comment] 2016-02-17 14:48
I confirmed that the "engine has no side" situation will make the game hang forever. I fixed it with a 35 second protocol initialization timeout that also ends the game (even if it's not yet started). I believe you won't get any more hangs after this.

But we still haven't figured out why the engine sometimes hangs or crashes, or communication with cutechess-cli fails to start.

**Comment by flok99** [comment] 2016-02-21 00:02
Hi,

With that version of 4 days ago I no longer saw hangs!
Note that this is without that xboard-program, just my programs.


On Wed, Feb 17, 2016 at 2:48 PM, Ilari Pihlajisto <notifications@github.com>
wrote:

> I confirmed that the "engine has no side" situation will make the game
> hang forever. I fixed it with a 35 second protocol initialization timeout
> that also ends the game (even if it's not yet started). I believe you won't
> get any more hangs after this.
>
> But we still haven't figured out why the engine sometimes hangs or
> crashes, or communication with cutechess-cli fails to start.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cutechess/cutechess/issues/27#issuecomment-185236317>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl

**Comment by mstembera** [comment] 2016-02-21 00:10
Sorry for the tangent but is the latest binary available anywhere?  Thank you.

**Comment by ilaripih** [comment] 2016-02-21 09:03
flok99: Good to hear! You may still have some "UciEngine(123) disconnects" or "UciEngine's connection stalls" errors in the cutechess log. But on the CuteChess side this issue is now fixed.

mstembera: Unfortunately we don't provide binaries for every commit; just for new releases. Fortunately it looks like we'll be releasing version 0.8.0 very soon.

**Comment by flok99** [comment] 2016-02-21 17:12
I had one case though where no pgn records where written. 2 out of 13.
Waited around 8 hours.
Op 21 feb. 2016 10:04 schreef "Ilari Pihlajisto" <notifications@github.com>:

**Comment by ilaripih** [comment] 2016-02-22 07:45
Damn, I'll reopen the issue.

What do you mean by "2 out of 13"? And by "no pgn records" do you mean that the pgn file wasn't even created or that it was left empty? And was cutechess still running after every game had finished?

**Comment by flok99** [comment] 2016-02-22 07:47
I had 13 systems running and two systems had this issue. No pgn was
created. Cutechess was still running and also played games (checked that
with the load).

On Mon, Feb 22, 2016 at 8:45 AM, Ilari Pihlajisto <notifications@github.com>
wrote:

> Damn, I'll reopen the issue.
>
> What do you mean by "2 out of 13"? And by "no pgn records" do you mean
> that the pgn file wasn't even created or that it was left empty? And was
> cutechess still running after every game had finished?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cutechess/cutechess/issues/27#issuecomment-187057041>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl

**Comment by ilaripih** [comment] 2016-02-22 07:54
Well that's a new one. When I get home I can check if the "engine has no side" problem could cause this. Did you see any "disconnects" or "connection stalls" errors in the logs of those two runs?

**Comment by ilaripih** [comment] 2016-02-22 17:49
I can confirm that something funny happens to the PGN output when the protocol initialization problem occurs. But on my machine it didn't result in no PGN file being created.

**Comment by flok99** [comment] 2016-02-24 21:21
Hi,

It took a bit but tonight it happened again. It is not very clear what it
is.

Since this new version I often got */? for the program-name:

Rank Name                          Elo    +    - games score oppo. draws
   1 Embla-lmr-2006c2b              83    8    8  3891   62%   -28   31%
   2 ?                               1 1318 1320   636   50%     1    3%
   3 Emblar2114-LMRval2-4_val1-1     1    8    8  4100   52%    -3   33%
   4 Emblar2114                    -17    8    8  4150   48%     3   39%
   5 Emblar2150_simple_threading   -68    8    8  4187   39%    20   27%

See nr. 2.

On Mon, Feb 22, 2016 at 5:49 PM, Ilari Pihlajisto <notifications@github.com>
wrote:

> I can confirm that something funny happens to the PGN output when the
> protocol initialization problem occurs. But on my machine it didn't result
> in no PGN file being created.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cutechess/cutechess/issues/27#issuecomment-187291031>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl

**Comment by ilaripih** [comment] 2016-02-25 13:22
Do you happen to have cutechess-cli debug logs of those runs? I can also try to analyze the code and try to find possible problems.

**Comment by ilaripih** [comment] 2016-02-26 16:20
I just pushed a commit "Better PGN output error handling" that will probably catch whatever write errors there may be, and reopen/recreate the file if something bad happens.

You'll need to re-build the whole cutechess project ("make distclean && qmake && make").

**Comment by ilaripih** [comment] 2016-02-29 08:06
If you get "?" or "*" as the engine name, it means that the engine failed to start and/or initialize the chess protocol in its last game. I think I can fix that quite easily. If the engine fails to start in every game then cutechess-cli never gets the name, but obviously that has not happened.

**Comment by flok99** [comment] 2016-02-29 08:10
Hi,

Sofar I could not reproduce it. It happens only occasionally.

On Thu, Feb 25, 2016 at 2:22 PM, Ilari Pihlajisto <notifications@github.com>
wrote:

> Do you happen to have cutechess-cli debug logs of those runs? I can also
> try to analyze the code and try to find possible problems.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cutechess/cutechess/issues/27#issuecomment-188782480>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl

**Comment by flok99** [comment] 2016-02-29 08:10
ok! cool!
Thanks for all the support by the way!

On Mon, Feb 29, 2016 at 9:06 AM, Ilari Pihlajisto <notifications@github.com>
wrote:

> If you get "?" or "*" as the engine name, it means that the engine failed
> to start and/or initialize the chess protocol in its last game. I think I
> can fix that quite easily. If the engine fails to start in every game then
> cutechess-cli never gets the name, but obviously that has not happened.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cutechess/cutechess/issues/27#issuecomment-190086251>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl

**Comment by ilaripih** [comment] 2016-02-29 18:02
I just pushed the commit that should fix the problem with the engine name.

**Comment by flok99** [comment] 2016-03-09 16:07
Hi,

Sofar it runs really great! Thanks!

Today I tried running my program (Embla), TSCP and FairyMax in a
tournament. Fairy-max doesn't work though. It starts, complains about the
level and easy commands and then cutechess-cli eventually times-out.

Wed Mar 9 17:04:34 CET 2016 STARTING test.sh of 2016-03-09
17:04:26.853815245 +0100
concurrency: 1
host: gallifrey
33 >XboardEngine(0): xboard
33 >XboardEngine(0): protover 2
41 >XboardEngine(1): xboard
41 >XboardEngine(1): protover 2
46 <XboardEngine(1): Tom Kerrigan's Simple Chess Program (TSCP)
46 <XboardEngine(1): version 1.81, 2/5/03
46 <XboardEngine(1): Copyright 1997 Tom Kerrigan
47 <XboardEngine(1): "help" displays a list of commands.
47 <XboardEngine(1): Opening book missing.
47 <XboardEngine(1): tscp>
47 <XboardEngine(1): Error (unknown command): protover
485 <XboardEngine(0): tellics say     Fairy-Max 4.8V
485 <XboardEngine(0): tellics say     by H.G. Muller
486 <XboardEngine(0): tellics say Gothic Chess is protected by U.S. patent
#6,481,716 by Ed Trice.
486 <XboardEngine(0): tellics say Falcon Chess is protected by U.S. patent
#5,690,334 by George W. Duke
Started game 1 of 3 (XboardEngine vs XboardEngine)
8082 >XboardEngine(0): new
8083 >XboardEngine(0): level 40 0:30 0.25
8083 >XboardEngine(0): post
8084 >XboardEngine(0): easy
8085 >XboardEngine(0): force
8085 >XboardEngine(1): new
8086 >XboardEngine(1): level 40 0:30 0.25
8087 >XboardEngine(1): post
8087 >XboardEngine(1): easy
8088 >XboardEngine(1): force
8089 >XboardEngine(0): time 3000
otim 3000
8090 >XboardEngine(0): go
8091 <XboardEngine(1): Error (unknown command): level
8092 <XboardEngine(1): Error (unknown command): easy
38101 >XboardEngine(0): ?
Terminating process of engine XboardEngine(0)
48120 >XboardEngine(1): result 0-1 {White's connection stalls}
48121 <XboardEngine(1): Error (unknown command): result
Finished game 1 (XboardEngine vs XboardEngine): 0-1 {White's connection
stalls}

*folkert@gallifrey ~/QueenBee $* cat test.sh
#! /bin/sh

NCPU=`lscpu | grep '^CPU.s.:' | awk '{ print $2; }'`
#CONC=$((NCPU / 2))
CONC=1
echo concurrency: $CONC

HOST=`hostname`
echo host: $HOST

cutechess-cli \
    -engine cmd=./E_2218.sh proto=uci \
    -engine cmd=/usr/games/fairymax proto=xboard \
    -engine cmd=/usr/local/bin/tscp181 proto=xboard \
    -concurrency $CONC \
    -each tc=40/30+0.25 dir=$DIR -rounds 1 -recover -pgnout out/$HOST.pgn
-site "$HOST" -debug



regards

On Mon, Feb 29, 2016 at 7:02 PM, Ilari Pihlajisto <notifications@github.com>
wrote:

> I just pushed the commit that should fix the problem with the engine name.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cutechess/cutechess/issues/27#issuecomment-190312914>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl

**Comment by ilaripih** [comment] 2016-03-10 07:11
Great to hear that it's running well!

Maybe the problem with Fairy-max is that it doesn't support decimal values for time increment. So with Fairy-max you'll probably have to use a full second increment.

**Comment by flok99** [comment] 2016-03-10 07:31
Hi,

I tried that but within cutechess-cli it hangs while if I enter it
manually, it works:

*folkert@gallifrey ~/QueenBee $* /usr/games/fairymax
tellics say     Fairy-Max 4.8V
tellics say     by H.G. Muller
tellics say Gothic Chess is protected by U.S. patent #6,481,716 by Ed Trice.
tellics say Falcon Chess is protected by U.S. patent #5,690,334 by George
W. Duke
new
level 40 0:30 1
post
easy
force
time 3000
otim 3000
go
# times @ 1601157070
# 16+16 pieces, centr = (1,1) R=40
 1      8        0          7 a2a4
 1     26        0          9 c2c4
 1     30        0         11 b1c3
 2      6        0         19 b1c3 c7c5
 2     15        0         93 d2d4 d7d5
 3     13        0        366 d2d4 d7d5 b1c3
 3     14        0        544 b1c3 c7c5 d2d4
 3     24        0        709 g1f3 c7c5 c2c4
 4     11        1       1410 g1f3 d7d5 d2d4 b8c6
 5      2        5       5106 g1f3 d7d5 d2d4 b8c6 b1c3
 5      3       15      14143 g1h3 d7d5 f2f4 c8f5 b1c3
 5      6       28      26540 b2b4 b8c6 c2c3 a7a5 d1a4
 5      9       35      32815 c2c4 d7d5 c4d5 d8d5 d2d4
 5     10       44      41624 d2d3 c7c5 b1c3 d7d5 c1f4
 5     12       59      55229 e2e4 d7d5 b1c3 g8f6 f2f3
 5     13       65      60232 f2f3 d7d5 b1c3 c7c5 a2a4
 5     17       77      72207 h2h4 d7d5 b1c3 c7c5 d2d4
 6      1       92      85511 h2h4 d7d5 b1c3 b8c6 d2d4 c8f5
 6      7      137     126466 g1f3 d7d5 d2d4 b8c6 b1c3 c8f5
# times @ 1601158803: real=1733 cpu=1740
# promo = 0 (`) GT = 0
move g1f3





On Thu, Mar 10, 2016 at 8:11 AM, Ilari Pihlajisto <notifications@github.com>
wrote:

> Great to hear that it's running well!
>
> Maybe the problem with Fairy-max is that it doesn't support decimal values
> for time increment. So with Fairy-max you'll probably have to use a full
> second increment.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cutechess/cutechess/issues/27#issuecomment-194709202>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl

**Comment by ilaripih** [comment] 2016-03-10 07:38
Oh sorry, now that I look at the previous debug log again, it's TSCP that throws the "Error (unknown command): level" error.

**Comment by ilaripih** [comment] 2016-03-10 07:40
But yes, Fairy-max hangs, ie. doesn't respond to the "go" command. I'll try it my self when I get home, maybe a buffering issue, etc.

**Comment by flok99** [comment] 2016-03-10 08:26
Looking forward to it!

I'm thinking: you send time 3000 and otim 3000 in one go (looking at the
log); maybe that is confusing things.

On Thu, Mar 10, 2016 at 8:40 AM, Ilari Pihlajisto <notifications@github.com>
wrote:

> But yes, Fairy-max hangs, ie. doesn't respond to the "go" command. I'll
> try it my self when I get home, maybe a buffering issue, etc.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cutechess/cutechess/issues/27#issuecomment-194718491>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl

**Comment by flok99** [comment] 2016-03-12 21:25
I would not expect to make any difference. And it doesn't :-) Fairymax cpu
usage goes to 100% so it does receive commands. I verified that it doesn't
go to 100% when no commands are invoked on it.
My guess is that it has to do with the time 3000 otim 3000 being send in
one go.

Furthermore, I verified that if I start fairymax and immediately, not
waiting at all (see below), it runs fine.

(cat t ; cat) | /usr/games/fairymax

where the file "t" contains:
new
level 40 0:30 0.25
post
easy
force
time 3000
otim 3000
go

fyi; the first cat statement sends the t-output to fairymax and the second
cat waits for input from stdin; that way stdin won't be closed immediately
after t has been sent.

On Thu, Mar 10, 2016 at 8:38 PM, Ilari Pihlajisto <notifications@github.com>
wrote:

> Fairy-Max 4.8V works on my 64-bit Ubuntu machine with cutechess-cli. Your
> debug output indicates that Fairy-Max didn't receive any input from
> cutechess-cli, not even the initial "xboard" and "protover 2" commands.
> Cutechess-cli thinks it successfully sent those commands. Can you try
> running a game with Fairy-Max by running cutechess-cli directly without the
> shell script?
>
> Could it be that cutechess-cli starts sending input to Fairy-Max too soon,
> and that breaks something in Fairy-Max?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cutechess/cutechess/issues/27#issuecomment-195036671>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl

**Comment by ilaripih** [comment] 2016-03-14 09:14
Can you try what happens if CuteChess sends the "time" and "otim" commands separately? The code is here: https://github.com/cutechess/cutechess/blob/master/projects/lib/src/xboardengine.cpp#L232

So it would become:

`write(QString("time %1").arg(csLeft));`
`write(QString("otim %1").arg(ocsLeft));`

**Comment by flok99** [comment] 2016-03-14 12:10
Hi,

It didn't help.
I did some stracing and such and found out that if "protover 2" is send to
fairymax, then when it reads fmax.ini it keeps trying to read even after
the end of the file is reached. So it is most likely a problem in fairymax
and not in cutechess-cli.
There are a couple of solutions: making the "protover 2" optional in cc-cli
and the other is fixing fairymax :-)

[...]

Ok I think I found the problem. It looks like a 'char' is on the raspberry
an unsigned value by default. I'll submit a fix to HGM. I'll put you in the
CC.
(well, after I've tested it of course)

On Mon, Mar 14, 2016 at 10:14 AM, Ilari Pihlajisto <notifications@github.com
> wrote:

> Can you try what happens if CuteChess sends the "time" and "otim" commands
> separately? The code is here:
> https://github.com/cutechess/cutechess/blob/master/projects/lib/src/xboardengine.cpp#L232
>
> So it would become:
>
> write(QString("time %1").arg(csLeft));
> write(QString("otim %1").arg(ocsLeft));
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cutechess/cutechess/issues/27#issuecomment-196215054>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl

**Comment by flok99** [comment] 2016-03-14 12:18
Yes, that's the problem.

On Mon, Mar 14, 2016 at 1:09 PM, Folkert van Heusden <mail@vanheusden.com>
wrote:

> Hi,
>
> It didn't help.
> I did some stracing and such and found out that if "protover 2" is send to
> fairymax, then when it reads fmax.ini it keeps trying to read even after
> the end of the file is reached. So it is most likely a problem in fairymax
> and not in cutechess-cli.
> There are a couple of solutions: making the "protover 2" optional in
> cc-cli and the other is fixing fairymax :-)
>
> [...]
>
> Ok I think I found the problem. It looks like a 'char' is on the raspberry
> an unsigned value by default. I'll submit a fix to HGM. I'll put you in the
> CC.
> (well, after I've tested it of course)
>
> On Mon, Mar 14, 2016 at 10:14 AM, Ilari Pihlajisto <
> notifications@github.com> wrote:
>
>> Can you try what happens if CuteChess sends the "time" and "otim"
>> commands separately? The code is here:
>> https://github.com/cutechess/cutechess/blob/master/projects/lib/src/xboardengine.cpp#L232
>>
>> So it would become:
>>
>> write(QString("time %1").arg(csLeft));
>> write(QString("otim %1").arg(ocsLeft));
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cutechess/cutechess/issues/27#issuecomment-196215054>
>> .
>>
>
>
>
> --
> www.vanheusden.com  www.slimwinnen.nl
>



-- 
www.vanheusden.com  www.slimwinnen.nl

**Comment by flok99** [comment] 2016-03-14 12:25
Hi,

Tried a match between my program Embla and FairyMax on a raspberry pi 2
using cutechess-cli.
This seemed to fail. Did some debugging and found out what was going wrong:

In PrintVariants() you store the result of fgetc in the variable 'c' -
which is defined as a char.
Now the problem is that on a rpi2 "char" is by default *unsigned*. Because
of that it would go into a endless loop as soon as you invoke "protover 2".
Now an unsigned char may sound strange but I think I read somewhere that
char is not per definition signed. Also fgetc() returns an int, so storing
its result in a char *can* give problems like these.
I've tried replacing char c by int c and it looks like this fixes the
problem.

void PrintVariants(int combo)
{
        int count=0, total=0, c=EOF+1; char buf[80];
        FILE *f;

        f = fopen(INI_FILE, "r");
        if(f==NULL) return 0;

        /* search for game names in definition file */
        do {
           while((c = fscanf(f, "Game: %s", buf)) != 1 && c != EOF)
               while((c = fgetc(f)) != EOF && c != '\n');
           if(c == EOF) break;
           total++;
           if(*buf < 'a' || combo == (strstr(buf, "fairy/") != buf))
continue;
           if(combo && count == 0) strcpy(selectedFairy, buf);
           if(count++) printf(combo ? " /// " : ",");
           printf("%s", combo ? buf+6 : buf);
        } while(c != EOF);

        fclose(f);
        if(!combo && total != count) printf("%sfairy", count ? "," : "");
}

FWIW if you do an strace on fairymax, you would see it doing read(3, "",
4096) (with result 0) over and over again; that's the stdio library calling
read() underneath (4kB because of buffering).

@vincent: this problem may affect other Debian release other than raspbian
as well.

On Mon, Mar 14, 2016 at 1:09 PM, Folkert van Heusden <mail@vanheusden.com>
wrote:

> Hi,
>
> It didn't help.
> I did some stracing and such and found out that if "protover 2" is send to
> fairymax, then when it reads fmax.ini it keeps trying to read even after
> the end of the file is reached. So it is most likely a problem in fairymax
> and not in cutechess-cli.
> There are a couple of solutions: making the "protover 2" optional in
> cc-cli and the other is fixing fairymax :-)
>
> [...]
>
> Ok I think I found the problem. It looks like a 'char' is on the raspberry
> an unsigned value by default. I'll submit a fix to HGM. I'll put you in the
> CC.
> (well, after I've tested it of course)
>
> On Mon, Mar 14, 2016 at 10:14 AM, Ilari Pihlajisto <
> notifications@github.com> wrote:
>
>> Can you try what happens if CuteChess sends the "time" and "otim"
>> commands separately? The code is here:
>> https://github.com/cutechess/cutechess/blob/master/projects/lib/src/xboardengine.cpp#L232
>>
>> So it would become:
>>
>> write(QString("time %1").arg(csLeft));
>> write(QString("otim %1").arg(ocsLeft));
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cutechess/cutechess/issues/27#issuecomment-196215054>
>> .
>>
>
>
>
> --
> www.vanheusden.com  www.slimwinnen.nl
>



-- 
www.vanheusden.com  www.slimwinnen.nl

**Comment by ilaripih** [comment] 2016-03-15 10:50
Awesome investigative work! Can I close this CuteChess issue?

**Comment by flok99** [comment] 2016-03-15 11:02
Yes! Thanks
Op 15 mrt. 2016 11:50 schreef "Ilari Pihlajisto" <notifications@github.com>:

**Closed** 2016-03-15 12:12 UTC
Labels: bug, lib
