### ISSUE TITLE
fischer random (chess960) movegen bug in cutechess-cli

### ISSUE THREAD

**Issue by kmar** [cutechess/cutechess#637] opened 2020-11-16 13:16 UTC
## Output of `cutechess-cli --version` / `cutechess --version`
cutechess-cli 1.2.0
## How did you run Cute Chess exactly?
cutechess-cli.exe -variant fischerandom -each option.Hash=32 -engine name=cheng4_dev cmd=cheng4a_x64.exe proto=uci tc=2+0.02 -openings file=chess960_book_3moves.pgn -engine name=cheng4_dev cmd=cheng4b_x64.exe proto=uci tc=2+0.02 -games 100000 -concurrency 8 -pgnout chengtest.pgn

## Expected behavior
allow legal FRC castling and don't allow to castle out of checkmate in FRC

## Actual behavior

the opposite of the above

## Steps to reproduce the behavior

please see the attached zipped pgn produced by cutechess-cli

this is where ccli doesn't allow a legal O-O-O for black
r1k1N2R/pp1pbr2/3p4/P7/8/2P2n2/1PBP4/RK6 b q - 4 28 

this is the FEN where black is checkmated but ccli thinks it's not
rk2Q3/1p4p1/1B6/4p3/p5p1/2Kp2P1/PP4P1/R7 b q - 0 34

**Screenshots**
not applicable

[frc_illegal.zip](https://github.com/cutechess/cutechess/files/5546413/frc_illegal.zip)

**Comment by rwbc** [comment] 2020-11-16 20:16
> 
> ## Output of `cutechess-cli --version` / `cutechess --version`
> 
> cutechess-cli 1.2.0
> ## How did you run Cute Chess exactly?
> 
> cutechess-cli.exe -variant fischerandom -each option.Hash=32 -engine name=cheng4_dev cmd=cheng4a_x64.exe proto=uci tc=2+0.02 -openings file=chess960_book_3moves.pgn -engine name=cheng4_dev cmd=cheng4b_x64.exe proto=uci tc=2+0.02 -games 100000 -concurrency 8 -pgnout chengtest.pgn
> ## Expected behavior
> 
> allow legal FRC castling and don't allow to castle out of checkmate in FRC
> ## Actual behavior
> 
> the opposite of the above
> ## Steps to reproduce the behavior
> 
> please see the attached zipped pgn produced by cutechess-cli
> 
> this is where ccli doesn't allow a legal O-O-O for black
> r1k1N2R/pp1pbr2/3p4/P7/8/2P2n2/1PBP4/RK6 b q - 4 28
> 
> this is the FEN where black is checkmated but ccli thinks it's not
> rk2Q3/1p4p1/1B6/4p3/p5p1/2Kp2P1/PP4P1/R7 b q - 0 34
> 
> **Screenshots**
> not applicable
> 
> [frc_illegal.zip](https://github.com/cutechess/cutechess/files/5546413/frc_illegal.zip)

Hi Martin,

This is already known and fixed e.g. in alweys fork EXPER1 branch.
Probably it will last some time until it will merged into the official cutechess.

https://github.com/cutechess/cutechess/issues/616

https://github.com/alwey/cutechess/commits/EXPER1

IIRC I have compiled already a version (win only) which has the fix in.

**Edit:**
Yes my compilation also has the cutechess-cli in, not only the CuteChess GUI.
It was announced in talkchess too ;)

http://talkchess.com/forum3/viewtopic.php?f=7&t=75249&hilit=cutechess#p863514

https://rwbc-chess.de/download.htm

**Comment by alwey** [comment] 2020-11-16 21:37
@kmar:
This is a good bug description. I tested both examples and indeed, both cases have already been fixed by PR #617. As @rwbc suggested, you can merge PR #617 into your build sources, or use my [EXPER1-branch](https://github.com/alwey/cutechess/commits/EXPER1) which also contains a bunch of other patches, or use EXPER1-branch binaries provided by @rwbc.

Duplicate of #616.

**Comment by lucasart** [comment] 2020-11-16 23:47
`O-O-O` and `O-O` are illegal notations and should be rejected by cutechess-cli. And so is SAN in general. The UCI protocol only accepts LAN, not SAN.

**Closed** 2020-11-17 06:42 UTC

**Comment by kmar** [comment] 2020-11-17 06:46
@lucasart: no idea what you mean. KxR is UCI standard and this is what Cheng plays, of course. I used SAN in the description because I find it easier to parse by humans, perhaps you're an exception :)

Anyway, I already closed the issue.
