### ISSUE TITLE
In tournament results some names are missing

### ISSUE THREAD

**Issue by mcostalba** [cutechess/cutechess#164] opened 2016-10-02 11:27 UTC
In tournament results some names are missing (the rank 0 is SF)

https://snag.gy/cuBJXp.jpg

**Comment by ilaripih** [comment] 2016-10-02 11:55
Is there a way to reproduce this or is it completely random when this happend? The tournament type seems to be Gauntlet?

**Comment by mcostalba** [comment] 2016-10-02 12:52
Yes it it is gauntlet. I am sorry I can't try again now, I am away from my
pc.

**Comment by ilaripih** [comment] 2016-10-02 14:15
I fixed one place in the code where the names could've been set to empty but I'm not sure if it fixes this issue because I couldn't reproduce it.

**Comment by mcostalba** [comment] 2016-10-02 14:21
Thanks I will check this. I have done nothing strange, just selected the
engines all in one go with ctrl + mouse click, only the last selected one
got the name.

**Comment by ilaripih** [comment] 2016-10-06 06:05
Did you find a way to reproduce the problem with the latest master?

**Comment by mcostalba** [comment] 2016-10-06 10:21
@ilaripih I will test this week-end when i'll come back home...

**Comment by mcostalba** [comment] 2016-10-08 07:09
I have retested this morning but i can't reproduce the bug anymore. Sorry, I have tested for about 10 times starting and stoppin a tournament but withouth any result.

**Comment by ilaripih** [comment] 2016-10-08 08:11
That sounds like my previous commit may have fixed it. I'm closing this issue, but please re-open if you encounter the bug again.

**Closed by ilaripih** 2016-10-08 08:11 UTC
Labels: bug, gui
