### ISSUE TITLE
(Bug) Cute Chess fails to remember window and elements positions between sessions

### ISSUE THREAD

**Issue by insanetesterftw** [cutechess/cutechess#170] opened 2016-10-05 13:16 UTC
Cute Chess fails to remember window and elements positions between sessions

Examples:

**Main window**
After arranging  the elements on the main window

![cutechessrememberpositionbefore1a_upload](https://cloud.githubusercontent.com/assets/11148841/19114188/d3599f16-8b04-11e6-97f4-ab754b2de1a7.png)

After restarting the application they have gone back to their original positions

![cutechessrememberpositionafter1a_upload](https://cloud.githubusercontent.com/assets/11148841/19114212/ebcb7a4c-8b04-11e6-8226-88d734919768.png)

**Tournament Settings**
After resizing the window

![tournamentwindowsizeandplacementa_upload](https://cloud.githubusercontent.com/assets/11148841/19114286/43ec55a2-8b05-11e6-8ade-49414523250c.png)

Notice how the elements on the window are not resized proportionally!

After restarting the application they have gone back to their original size

![tournamentwindowsizeandplacementb_upload](https://cloud.githubusercontent.com/assets/11148841/19114334/87f9e890-8b05-11e6-8891-99a52a0256de.png)

Notice how, by default, the elements are not proportionally to each other and the **Players** element is too small!

**Comment by ilaripih** [comment] 2016-10-06 06:35
It may be best to only resize the "Players" element when resizing NewTournamentDialog. Or making "Players" a bit wider by default and disabling resizing completely.

Regarding restoring MainWindow geometry from the previous session: it should work, but I've found that it's not completely reliable when the Cute Chess window is maximized. I'll see if there's something I can do about it.

**Comment by insanetesterftw** [comment] 2016-11-07 15:51
> Regarding restoring MainWindow geometry from the previous session: it should work, but I've found that it's not completely reliable when the Cute Chess window is maximized. I'll see if there's something I can do about it.

Based on your comment the following method worked:
- Resize the **MainWindow** to be as close to maximized as possible
- Resize the panels to your taste
- Close application
- Start application, your settings from the previous session survived
- Maximize application
- Close application
- Start application, your settings are still respected

It's clear that if we resize the panels while the **MainWindow** is maximized then the settings will not be preserved between sessions. But if we rearranged the panels and only then maximize the **MainWindow** they will.

> It may be best to only resize the "Players" element when resizing NewTournamentDialog. Or making "Players" a bit wider by default and disabling resizing completely.

The **NewTournamentDialog** has three problems:
- It will not remember resize settings
- The elements **General Information** and **Players** are too thin by default
- If we resize the **NewTournamentDialog** the **General Information** element will grow at bigger rate than the **Players** element. The **General Information** element becomes disproportionally bigger than the other two elements, as we can see in the picture in my first comment.

If you cannot make these subwindows remember their user resize settings then my advise it to resize the **General Information** element and the **Players** to match the size of the **Games** element and don't allow the user to modified it.

By the way, other subwindows or dialogs also don't remember their user resized positions. The **Configure Engine** dialog should have the same size of the **Settings** dialog.

**Comment by artoj** [comment] 2017-07-17 17:57
I cannot reproduce the MainWindow resize issue on MacOS Sierra with Qt 5.9.1.

**Comment by ilaripih** [comment] 2017-07-18 08:57
Looks like this doesn't have much to do with the `BoardView` widget but is related to Qt's central widget concept. I guess we could use a 0-sized placeholder widget as the central widget to solve this problem.

**Comment by ilaripih** [comment] 2017-07-18 12:02
Confirmed to be a Qt bug: https://bugreports.qt.io/browse/QTBUG-16252
Workaround deployed. Closing.

**Closed by ilaripih** 2017-07-18 12:02 UTC
Labels: bug, gui
