### ISSUE TITLE
Swiss tournament

### ISSUE THREAD

**Issue by Krzychumag** [cutechess/cutechess#659] opened 2021-03-27 09:08 UTC
Once again, please, please add a Swiss tournament that you can play it in the program.

**Comment by alwey** [comment] 2021-06-10 16:41
It does not help to repeat this request.

This is a duplicate of open issue #267, and of your issue #542.

**Comment by artoj** [comment] 2022-11-22 18:51
Closed as duplicate

**Closed by artoj** 2022-11-22 18:51 UTC
