### ISSUE TITLE
General (global) setting to disable usage of opening books and end game databases independently of engine settings

### ISSUE THREAD

**Issue by insanetesterftw** [cutechess/cutechess#168] opened 2016-10-05 12:02 UTC
General (global) setting applying to all engines disabling their usage of opening books and end game databases independently of their own settings

There isn't any information while games are being played if engines use opening books or end game databases and I want to make sure that they aren't being used.

Setting each engine individually is inefficient if one has hundreds of them.

**Comment by ilaripih** [comment] 2016-10-06 06:24
Tablebase hits are going to be shown in realtime engine statistics: https://github.com/cutechess/cutechess/issues/74

This is mostly a duplicate of issue #143. Please continue the discussion there. I'm closing this one.

**Closed by ilaripih** 2016-10-06 06:24 UTC
Labels: duplicate
