### ISSUE TITLE
non-gauntlet mode: stops emitting .pgn-entries after termination

### ISSUE THREAD

**Issue by flok99** [cutechess/cutechess#205] opened 2017-02-27 12:09 UTC
Situation: cutechess-cli runs a non-gauntlet tournament.
One program is terminated "Terminating process of engine dorpsgek(12)" (the program apparently hung after a protover 2). After that the tournament continues(!) but no pgn-entries are written anymore.

`cutechess-cli -engine cmd=/usr/local/bin/dorpsgek proto=xboard name=dorpsgek -engine cmd=/usr/games/fairymax proto=xboard name=fairymax -engine cmd=./E_097.sh proto=uci name=0.9.7 -engine cmd=./E_trunk.sh proto=uci -engine cmd=./E_trunk-3881.sh proto=uci -engine cmd=/usr/local/bin/floyd proto=uci -concurrency 12 -each dir= tc=40/5+0.125 -rounds 500 -recover -pgnout out/belle.pgn -site belle -debug`

**Comment by ilaripih** [comment] 2017-02-27 13:05
Because of `-recover` the tournament is supposed to continue. But yeah, the stopping of PGN output looks like a bug.

**Comment by ilaripih** [comment] 2017-07-17 19:41
Could not reproduce with the latest code - the games keep getting written to the PGN file.

**Comment by ilaripih** [comment] 2017-07-18 12:04
At this point we need more information about exactly how to reproduce the issue, eg. at what exact point should an engine become unresponsive? The debug logs would also be really helpful.

**Comment by alwey** [comment] 2018-07-07 12:47
Possibly the PGN ouput gets blocked in order to output a complete round of games.

**Comment by ilaripih** [comment] 2018-07-07 13:55
Sounds reasonable. In that case I think I may have fixed this bug when I fixed this one: https://github.com/cutechess/cutechess/issues/293

**Comment by alwey** [comment] 2018-07-07 14:54
Yes, very likely.

**Comment by ilaripih** [comment] 2018-07-07 15:02
I'll close this for now but if someone can reproduce the bug with the latest master then the issue should be re-opened.

**Closed by ilaripih** 2018-07-07 15:02 UTC
Labels: bug, lib, needs-info
