### ISSUE TITLE
Feature: import PGN and analyze game

### ISSUE THREAD

**Issue by Zibri** [cutechess/cutechess#726] opened 2022-06-08 13:54 UTC
It seems this is the main missing feature.
Just saying...

**Comment by alwey** [comment] 2022-06-09 09:01
Hello, thank you for your feedback. This feature request is essentially a duplicate of #13. Please close this issue.

**Comment by artoj** [comment] 2022-06-11 12:14
Closed as duplicated.

**Closed** 2022-06-11 12:14 UTC
