### ISSUE TITLE
Game abandoned: {White's connection stalls}

### ISSUE THREAD

**Issue by 0qln** [cutechess/cutechess#767] opened 2023-07-28 22:03 UTC
## Output of `cutechess-cli --version`
Using Qt version 5.11.1

Copyright (C) 2008-2020 Ilari Pihlajisto, Arto Jonsson and contributors
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

## How did you run Cute Chess exactly?
1. `cd` to the directory containing the `cutechess-cli.exe` file
2. Run some command to test the engine: `.\cutechess-cli.exe -engine cmd="D:\stockfish\stockfish-windows-x86-64-avx2\stockfish\stockfish-windows-x86-64-avx2.exe" -engine cmd="D:\stockfish\stockfish-windows-x86-64-avx2\stockfish\stockfish-windows-x86-64-avx2.exe" -each proto=xboard tc=40/20 -rounds 5`

Include the full command-line used to run the application. In case the `-conf` parameter was used, include the relevant engine configurations from the configuration file.

## Expected behavior

Run a match of the specified engine of 5 rounds.

## Actual behavior

```
Started game 1 of 5 (XboardEngine vs XboardEngine)
Terminating process of engine XboardEngine(0)
...      XboardEngine playing White: 0 - 1 - 0  [0.000] 1
...      White vs Black: 0 - 1 - 0  [0.000] 1
Elo difference: -inf +/- nan, LOS: 15.9 %, DrawRatio: 0.0 %
Finished match
Finished game 1 (XboardEngine vs XboardEngine): 0-1 {White's connection stalls}
Score of XboardEngine vs XboardEngine: 0 - 1 - 0  [0.000] 1
```

## Steps to reproduce the behavior
1. `cd` to the directory containing the `cutechess-cli.exe` file
2. Run : `.\cutechess-cli.exe -engine cmd="D:\stockfish\stockfish-windows-x86-64-avx2\stockfish\stockfish-windows-x86-64-avx2.exe" -engine cmd="D:\stockfish\stockfish-windows-x86-64-avx2\stockfish\stockfish-windows-x86-64-avx2.exe" -each proto=xboard tc=40/20 -rounds 5`

**Screenshots**
![image](https://github.com/cutechess/cutechess/assets/129159411/3cdfbd42-2204-4900-935f-d75089685aa8)

**Comment by artoj** [comment] 2023-07-29 05:23
Can you try to reproduce this with the latest version, 1.3.0?

**Comment by ilaripih** [comment] 2023-07-29 06:14
Actually the issue seems to be that you're trying to run Stockfish as an XBoard engine. Stockfish is a UCI engine, so try `proto=uci` instead of `proto=xboard`.

**Comment by artoj** [comment] 2023-07-29 08:15
Closing as per above.

**Closed by artoj** 2023-07-29 08:15 UTC
