### ISSUE TITLE
Cute Chess 1.0.0 - question

### ISSUE THREAD

**Issue by Krzychumag** [cutechess/cutechess#250] opened 2017-08-07 07:13 UTC
During a tournament on the site http://tcec.chessdom.com/live.php of the engine author Robert Houdart wrote that in the application cutechess-cli is an error. The problem is showing mat while playing. Whether this error still occurs or not in the application Cute Chess 1.0.0.

**Comment by ilaripih** [comment] 2017-08-07 07:23
Do you know what the error is or do you have a direct link to the message where the error is described?

**Comment by Krzychumag** [comment] 2017-08-07 07:47
Thank you for your answer ilaripih. As for the mistake this was written by the author engine Houdini - Robert Houdart. Please look here http://tcec.chessdom.com/archive.php 
![tcec](https://user-images.githubusercontent.com/30792281/29017037-5a14fcda-7b55-11e7-9ec6-9531ad08e826.jpg)

**Comment by alwey** [comment] 2017-08-07 15:29
Sadly, without debug log we cannot see exactly what happened, which value _Houdini 5_ as Black transferred to the (albeit modified for TCEC) cutechess-cli. I am not sure whether TCEC saves debug logs of the tournaments. Perhaps somebody with Houdini 5 encounters similar behaviour and can provide debug logs?

This is the endgame of TCEC Season 9 Superfinal, game number 5.

```
53. Ke3 { d=41, pd=a5, mt=00:02:28, tl=00:40:42, s=92378 kN/s, n=13751648513, pv=Ke3 a5 Nh2 Bf5 Rg1 a3 bxa3 Be4 Nf1 Kh6 Nd2 Bc2 Rc1 Bf5 Rc5 a4 Rxd5 Bg4 Nf3 Ne7 Re5 Ng8 Kf4 Nf6 Ra5 Bh3 Rg5 Bc8 Rg1 Nd5+ Ke4 
Bb7 Nd4 Nb6+ Ke5 Ba8 Kf4 Nd5+ Kf5 Nc3 Ke5 Kh5 Nf5 Nd5 Rg3 Nc7 Rg7 Nd5 Ra7 Bc6 Nd4 Nc3 Nxc6 Kg5 Rg7+ Kh6 Rg1, tb=512
19291, R50=49, wv=9.58, }
Ne7 { d=29, pd=Rg1, mt=00:02:47, tl=00:24:41, s=101138 kN/s, n=16910474849, pv=Ne7 Rg1, tb=374351, R50=48, wv=2.64, }
54. Rg1 { d=42, pd=Bc8, mt=00:01:49, tl=00:39:08, s=95812 kN/s, n=10483217996, pv=Rg1 Bc8 Kd4 Bh3 Kc5 Ng6 Kd6 Nf4 Rg5+ Kh6 Rg3 Bf5 Ke5 Nh5 Rg1 Be4 Nd4 Kh7 Ne6 Bc2 Kxd5 Nf6+ Kd6 Bb3 Nd4 Ba2 Nf5 Nd5 Ra1 Nb4 Nd4 Bf7 Rxa4 Nd3 Rxa6 Nf2 Ra5 Bg6 b4 Ne4+ Kc7 Nf6 b5 Nd5+ Kc6 Ne3 Ra7+ Kg8 Kc5 Bd3 b6 Nd1 Ra8+ Kf7 b7 Ne3 b8=Q, tb=31257203, R50=48, wv=14.29, }
Nc6 { d=32, pd=Rc1, mt=00:03:47, tl=00:21:08, s=102748 kN/s, n=23337232492, pv=Nc6 Rc1, tb=1053235, R50=47, wv=3.98, }
55. Rc1 { d=40, mt=00:01:07, tl=00:38:15, s=91263 kN/s, n=6169147664, pv=Rc1, tb=42821829, R50=47, wv=123.72, }
Nb4 { d=36, pd=Ne5, mt=00:03:55, tl=00:17:28, s=102598 kN/s, n=24155030734, pv=Nb4 Ne5, tb=2836011, R50=46, wv=8.17, }
56. Rh1+ { d=67, pd=Kg6, mt=00:01:37, tl=00:36:53, s=80534 kN/s, n=7873800369, pv=Rh1+ Kg6 Ne5+ Kf5 Nxg4 Kxg4 Rf1 Nc2+ Kd3 Nb4+ Kd2 Kg5 Rf7 Nc6 Rd7 Nb4 Rb7 Nc6 Rb6 Na5 Rxa6 Nb3+ Kc2 Nc5 Ra5 Nb3 Rxa4, tb=176789221, R50=46, wv=128.40, }
Kg6 { d=40, pd=Ne5+, mt=00:01:48, tl=00:15:55, s=109096 kN/s, n=11783938845, pv=Kg6 Ne5+ Kf5 Nxg4 Nc2+ Kd3 Nb4+ Kc3 a5 Ne3+ Kg5 Kd4 Nc6+ Kxd5 Nb8 Rg1+ Kf6 Kd6 Kf7 Nd5 a3 bxa3 Na6 Rf1+ Kg6 Ne7+ Kh6 Rf8 a4 Ra8 Nb8 Rxb8, tb=9725192, R50=45, wv=M1, }
57. Ne5+ { d=75, pd=Kf5, mt=00:00:29, tl=00:36:38, s=84332 kN/s, n=2490001740, pv=Ne5+ Kf5 Nxg4 Kxg4 Rf1 Nc2+ Kd3 Nb4+ Kd2 Kg5 Rf7 Nc6 Rd7 Nb4 Rb7 Nc6 Rb6 Na5 Rxa6 Nb3+ Kc2 Nc5 Ra5 Nb3 Rxa4, tb=44388454, R50=45, wv=128.41, }
Kf5 { d=41, pd=Nxg4, mt=00:01:11, tl=00:14:58, s=117166 kN/s, n=8397117392, pv=Kf5 Nxg4 Nc2+ Kd3 Nb4+ Kc3 a5 Ne3+ Kg5 Rg1+ Kh6 Kd4 Nc6+ Kxd5 a3 bxa3 Ne7+ Kd6 Nc8+ Ke5 Kh5 Kf4 Ne7 Rg5+ Kh6 Nf5+ Nxf5, tb=5755894, R50=44, wv=M1, }
58. Nxg4 { d=83, pd=Kxg4, mt=00:01:45, tl=00:35:08, s=103220 kN/s, n=10884554215, pv=Nxg4 Kxg4 Rf1 Nc2+ Kd3 Nb4+ Kd2 Kg5 Rf7 Nc6 Rd7 Nb4 Rb7 Nc6 Rb6 Na5 Rxa6 Nb3+ Kc2 Nc5 Ra5 Nb3 Rxa4, tb=114701224, R50=44, wv=128.41, }
a3 { d=41, pd=bxa3, mt=00:00:53, tl=00:14:20, s=109560 kN/s, n=5846787905, pv=a3 bxa3 Na2 Kd4 Kg5 Ne3 Kf4 Ra1 Nc3 Rf1+ Kg5 Rg1+ Kf4 Kxc3 Kxe3, tb=4191765, R50=50, wv=M1,, White wins by adjudication: TCEC win rule }
1-0

```

**Comment by Krzychumag** [comment] 2017-08-07 17:17
Well, that's why Eval is **M1**

**Comment by alwey** [comment] 2017-08-07 17:29
@Krzychumag: cutechess-cli wrote out `M1` but we do not know which value _Houdini 5_ transferred to cutechess-cli.

**Comment by ilaripih** [comment] 2017-08-07 17:45
If I recall correctly the TCEC version of cutechess-cli is really old and drifted quite a lot from the official repo.

**Comment by Krzychumag** [comment] 2017-08-07 17:50
He does not quite understand it. Unfortunately, the problem appears during the game. I do not know if this is the fault of the application Cute Chess 1.0.0 or the chess engine itself. Below you will find a test game.

[Event "My Tournament"]
[Site "Test"]
[Date "2017.08.07"]
[Round "1"]
[White "Houdini 5.01 Pro x64"]
[Black "Equinox 3.30 x64"]
[Result "1-0"]
[ECO "B12"]
[Opening "Caro-Kann"]
[PlyCount "147"]
[TimeControl "300"]
[Variation "Advance Variation"]

1. e4 {book} c6 {book} 2. d4 {book} d5 {book} 3. e5 {book} c5 {book} 4. dxc5 {book} e6 {book} 5. Be3 {+0.30/18 10s} Nh6 {-0.28/22 19s} 6. Bd4 {+0.30/20 6.9s} Bd7 {-0.21/22 27s} 7. c3 {+0.18/20 7.4s}
Nc6 {-0.12/21 3.6s} 8. Nf3 {+0.21/18 6.0s} Nf5 {-0.18/21 20s} 9. Qd2 {+0.23/19 4.9s} g6 {-0.19/20 11s} 10. Bb5 {+0.12/18 0.87s} Bh6 {-0.15/20 7.7s} 11. Qe2 {+0.46/18 4.5s} a6 {-0.23/21 2.4s} 12. Bxc6 {+0.69/18 2.8s} bxc6 {-0.29/21 3.6s} 13. h4 {+0.63/22 6.9s} Rb8 {-0.22/20 8.5s} 14. g4 {+1.04/18 3.4s} Nxd4 {-0.49/21 6.3s} 15. cxd4 {+0.38/18 9.2s} Bf4 {-0.59/22 11s} 16. h5 {+0.48/18 4.0s} g5 {-0.39/19 6.6s} 17. Nc3 {+0.43/20 7.5s} O-O {-0.30/19 2.4s} 18. O-O {+0.31/19 6.9s} f6 {-0.34/20 12s} 19. b3 {+0.24/19 6.9s} a5 {-0.36/20 11s} 20. Na4 {+0.22/20 12s} Bc8 {-0.41/21 5.6s} 21. Nb6 {+0.48/20 3.0s} f5 {-0.45/21 5.8s} 22. Nxc8 {+0.60/20 3.9s} Qxc8 {-0.45/23 7.8s} 23. Ne1 {+0.71/20 4.7s} fxg4 {-0.43/22 1.8s} 24. Nd3 {+0.54/21 8.8s} h6 {-0.41/21 4.0s} 25. Qxg4 {+0.65/19 3.2s} Qd7 {-0.41/21 1.7s} 26. Rad1 {+0.60/22 6.5s} Rbe8 {-0.49/21 6.4s} 27. Rfe1 {+0.84/21 4.0s} Qa7 {-0.44/20 7.2s} 28. Re2 {+0.70/20 1.3s} a4 {-0.55/23 13s} 29. b4 {+0.75/23 8.2s} Qa6 {-0.56/23 6.1s} 30. Rc2 {+0.75/24 6.9s} Qb7 -0.53/22 1.1s} 31. a3 {+0.71/23 7.8s} Qh7 {-0.61/21 5.0s} 32. b5 {+1.01/24 22s} Qe4 {-0.54/20 2.6s} 33. Qe2 {+1.01/22 0.038s} Qf5 {-0.43/19 1.2s} 34. Kg2 {+1.33/18 2.2s} cxb5 {-0.43/17 0.12s} 35. f3 {+1.33/16 0s} Kh8 {-0.87/18 6.7s} 36. Nf2 {+1.58/19 2.9s} g4 {-1.44/19 5.7s} 37. fxg4 {+1.62/20 6.3s} Rg8 {-1.44/19 0.63s} 38. Kh3 {+1.87/19 13s} Qh7 {-1.61/18 3.9s} 39. Rd3 {+1.65/21 13s} Qf7 {-1.78/18 2.9s} 40. c6 {+1.63/20 6.0s} Rc8 {-1.79/20 3.7s} 41. Rf3 {+2.02/21 8.2s} Rxg4 {-1.77/19 0.65s} 42. Nxg4 {+2.02/19 0.001s} Qxh5+ {-1.77/18 0.025s} 43. Kg2 {+2.02/1 0s} Qxg4+ {-1.81/20 1.1s} 44. Kf1 {+2.15/19 1.4s} Qh4 {0.50s} 45. Qg2 {+2.58/19 1.7s} Bg5 {-2.69/20 11s} 46. Rf7 {+2.75/18 1.5s} Qh5 {-2.78/20 6.2s} 47. Qf3 {+2.75/17 0s} Qxf3+ {-2.78/19 0.073s} 48. Rxf3 {+2.92/19 1.7s} Kg7 {-2.75/21 2.1s} 49. Rfc3 {+3.08/20 1.3s} Kg6 {-2.89/20 0.48s} 50. Rb2 {+3.08/18 0.005s} Bd8 {-3.03/19 0.49s} 51. Ke2 {+3.23/18 1.3s} h5 {-3.14/19 1.4s} 52. Rxb5 {+3.38/18 1.1s} Kf5 {-3.97/22 9.5s} 53. Kf3 {+3.71/19 1.4s} h4 {-3.96/22 6.8s} 54. Rb1 {+4.08/18 1.0s} Ba5 {-4.67/19 4.8s} 55. Rc2 {+3.91/24 4.3s} Rg8 {-4.67/20 0.80s} 56. Rg2 {+3.84/24 0.030s} Rxg2 {-4.67/19 0.026s} 57. Kxg2 {+4.36/22 1.2s} Ke4 {-4.67/20 0.25s} 58. Rb4 {+5.02/18 0.96s} Bd8 {-4.67/21 0.46s} 59. Rxa4 {+7.01/19 0.93s} Bb6 60. Rb4 {+8.51/19 0.93s}
Bd8 {-7.89/20 3.0s} 61. Kh3 {+9.83/18 0.86s} Kd3 {-10.66/19 2.1s} 62. Rb7 {+14.64/18 0.86s} Ba5 {-15.12/17 1.5s} 63. c7 {+80.52/18 2.0s} Bxc7 {-16.68/16 0.15s} 64. Rxc7 {+M1/30 0.86s} Kxd4 {-116.93/17 1.0s} 65. a4 {+M37/20 0.25s} Ke3 {-115.30/14 0.11s} 66. a5 {+M25/26 0.93s} Kf4 {-M44/16 0.22s} 67. a6 {+M23/29 1.2s} Kf3 {-M32/17 0.14s} 68. a7 {+M15/23 0.068s} Ke4 {-M26/17 0.64s} 69. a8=Q {+M13/21 0.084s} Ke3 {-M14/15 0.44s} 70. Qa1 {+M9/18 0.037s} d4 {-M32/10 0.024s} 71. Qe1+ {+M7/16 0.011s} Kd3 {-M6/16 0.047s} 72. Kg2 {+M5/14 0.003s} h3+ {-M4/46 0.023s} 73. Kf1 {+M3/12 0.002s} h2 {-M2/62 0.008s} 74. Qe2# {+M1/11 0.003s, White mates} 1-0

Please look at the movement 64. Rxc7 {+M1/30 0.86s}. That is why I have given this problem to be resolved.

**Comment by alwey** [comment] 2017-08-07 17:58
@Krzychumag : Please consider to reopen this issue. I think that we have a chance to clarify this.

**Comment by Krzychumag** [comment] 2017-08-07 18:12
I understand that there is an old version cutechess-cli. But during the application tests this problem also appeared.

**Comment by alwey** [comment] 2017-08-07 18:14
OK, Houdini will have transferred a value higher than 99.00 and close to x*10.00, e.g. 99.99 - this gives M1.

**Comment by Krzychumag** [comment] 2017-08-07 18:21
ilaripih can you please open the topic and not close it?

**Comment by Krzychumag** [comment] 2017-08-07 18:22
@alwey and from where do you have such calculations.

**Comment by ilaripih** [comment] 2017-08-07 18:32
@Krzychumag I didn't close the issue, you did. But I can reopen it.

**Comment by alwey** [comment] 2017-08-07 18:35
@Krzychumag : Use the source, Luke.

**Comment by Krzychumag** [comment] 2017-08-07 18:43
@ ilaripih - Thank you, I guess by mistake I closed the post.
@alwey - such an approach and calculation for the first time I see. So, in your opinion, the chess engine is guilty and not the application Cute Chess 1.0.0.

**Comment by alwey** [comment] 2017-08-07 18:45
@Krzychumag : 

>such an approach and calculation for the first time I see. So, in your opinion, the chess engine is guilty and not the application Cute Chess 1.0.0.

No, it is not. We have to think about this.

**Comment by alwey** [comment] 2017-08-07 18:47
The problem is, that chess engines have different ideas to signalise mate scores. I think we'll find a solution.

**Comment by Krzychumag** [comment] 2017-08-07 18:54
@alwey I'm sorry to ask you and you are a programmer program Cute Chess 1.0.0.

**Comment by alwey** [comment] 2017-08-07 19:08
@Krzychumag : 

>I'm sorry to ask you and you are a programmer program Cute Chess 1.0.0.

I am only a contributor, and this project needs feedback from the users, so you helped us already by pointing this out. Thank you for doing this. The authorities of this project are @ilaripih  and @artoj .

**Comment by Krzychumag** [comment] 2017-08-07 19:26
> I am only a contributor, and this project needs feedback from the users, so you helped us already by pointing this out. Thank you for doing this. The authorities of this project are @ilaripih and @artoj .

Thank you for your answer. And you do not know when there will be a new version Cute Chess.

**Comment by alwey** [comment] 2017-08-07 19:43
@Krzychumag ;
>you do not know when there will be a new version Cute Chess.

Not really.

I think it depends on the maintainers having enough time for a release and judging that stability and progress of the software were favourable.

**Comment by ilaripih** [comment] 2017-08-08 07:27
The UCI protocol actually does define a way for engines to report mate scores so I guess this bug is totally fixable. Cute Chess understands the UCI mate scores but converts them into Xboard-style values: https://github.com/cutechess/cutechess/blob/master/projects/lib/src/uciengine.cpp#L416

**Comment by alwey** [comment] 2017-08-09 13:16
>The UCI protocol actually does define a way for engines to report mate scores so I guess this bug is totally fixable.

I would call this issue "Possible collision of high UCI scores and Xboard mate scores" .

**Comment by ilaripih** [comment] 2017-08-30 06:26
This issue was fixed by @alwey

**Closed by ilaripih** 2017-08-30 06:26 UTC
Labels: needs-info
